= GitHub Connector Release Notes
:keywords: release notes, github, connector

*Community*

Anypoint Connector for GitHub provides integration with GitHub services through the link:https://github.com/eclipse/egit-github/tree/master/org.eclipse.egit.github.core[GitHub Java API].

Guide: link:/mule-user-guide/v/3.7/github-connector[GitHub Connector]

=== Version 3.0.0 - October 14, 2015

=== Contents

. Compatibility
. Features
. Fixed in this Release
. Known Issues
. Support Resources 

Release Notes for version 3.0.0 of the GitHub Connector. These Release Notes accompany the link:/mule-user-guide/v/3.7/github-connector[GitHub Connector Documentation Guide].
 
=== Compatibility
The GitHub Connector is compatible with:

|===
|Application/Service|Version
|Mule Runtime|3.6.x or higher
|GitHub API|3
|Eclipse EGit GitHub API Core|2.1.5
|Java|1.7.0_x
|Anypoint Studio|5.2 or higher
|===

=== Features

* *Test Connectivity* to enable an early test of the connection when configuring the connector.

* *DataWeave* support.

* New *demo* examples.

=== Fixed in this Release

None.

=== Known Issues

None.

=== Support Resources

None.
